### ISSUE TITLE
couldn't find "libnative-lib.so"

### ISSUE THREAD

**Issue by Adeeb123456** [junyuecao/AndroidSoundTouch#5]
FATAL EXCEPTION: Thread-2
                                                                                        Process: io.github.junyuecao.androidsoundeffect, PID: 32172
                                                                                        java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/io.github.junyuecao.androidsoundeffect-RagChzYBVh0cIkVDb0OSXw==/base.apk"],nativeLibraryDirectories=[/data/app/io.github.junyuecao.androidsoundeffect-RagChzYBVh0cIkVDb0OSXw==/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libnative-lib.so"
                                                                                            at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
                                                                                            at java.lang.System.loadLibrary(System.java:1657)
                                                                                            at io.github.junyuecao.soundtouch.SoundTouch.<clinit>(SoundTouch.java:13)
                                                                                            at io.github.junyuecao.androidsoundeffect.MainActivity.onVoiceStart(MainActivity.kt:34)
                                                                                            at io.github.junyuecao.androidsoundeffect.VoiceRecorder$ProcessVoice.run(VoiceRecorder.java:188)
                                                                                            at java.lang.Thread.run(Thread.java:764)

**Comment by junyuecao** [comment]
Did you build the apk from source or install the demo?

**Comment by elirehema** [comment]
https://stackoverflow.com/a/49310471/7098524

**Comment by varun-goyal-stack** [comment]
Hi @junyuecao @Adeeb123456 @elirehema
 Please let me know if there is any fix for this crash.

 
 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/-kman3Vrrf8oQ8wwB2JJtFw==/base.apk"],nativeLibraryDirectories=[/data/app/-kman3Vrrf8oQ8wwB2JJtFw==/lib/x86_64, /data/app/-kman3Vrrf8oQ8wwB2JJtFw==/base.apk!/lib/x86_64, /system/lib64, /system/product/lib64]]] couldn't find "libnative-lib.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at io.github.junyuecao.soundtouch.SoundTouch.<clinit>(SoundTouch.java:13)
